#!/usr/bin/env python3
"""Build every figure and every quoted number of the 2026-07-28 weekly report from the
run artifacts on HF (`efeyenice/pc-completion-data`, public). Prose numbers are emitted as
LaTeX macros (generated/numbers.tex) so the report text cannot drift from the data."""
import os
import numpy as np
import pandas as pd

os.environ.setdefault("SOURCE_DATE_EPOCH", "1785196800")  # deterministic PDF metadata
import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.ticker import NullFormatter, NullLocator

def logx(ax):
    ax.set_xscale("log"); ax.xaxis.set_minor_formatter(NullFormatter()); ax.xaxis.set_minor_locator(NullLocator())

from PIL import Image
from huggingface_hub import HfApi, hf_hub_download

REPO = "efeyenice/pc-completion-data"
HERE = os.path.dirname(os.path.abspath(__file__))
FIG = os.path.join(HERE, "figures")
GEN = os.path.join(HERE, "generated")
os.makedirs(FIG, exist_ok=True)
os.makedirs(GEN, exist_ok=True)

ARMS = ["A_geo", "B_joint", "C_colin"]
ARM_STYLE = {  # color, marker, pretty label
    "A_geo": ("#1F3A5F", "o", "A_geo (xyz$\\to$xyz)"),
    "B_joint": ("#2E7D32", "^", "B_joint (xyzrgb$\\to$xyzrgb)"),
    "C_colin": ("#C05621", "s", "C_colin (xyzrgb$\\to$xyz)"),
}
SIZES = [20, 60, 150]


def dl(path):
    return hf_hub_download(REPO, path, repo_type="dataset")


# ---------------- data ----------------
curve = pd.read_csv(dl("runs/curve.csv"))
run_of = lambda r: f"n{int(r.n_per_cat):03d}_{r.arm}_s{int(r.seed)}"
curve["run"] = curve.apply(run_of, axis=1)
metrics = {r: pd.read_csv(dl(f"runs/{r}/metrics.csv")) for r in curve["run"]}
api = HfApi()
dataset_sha = api.dataset_info(REPO).sha
n_bundles = sum(1 for f in api.list_repo_files(REPO, repo_type="dataset") if f.startswith("data/"))

mean_cd = {(n, a): curve[(curve.n_per_cat == n) & (curve.arm == a)].test_cd_l1.mean() for n in SIZES for a in ARMS}
mean_fs = {(n, a): curve[(curve.n_per_cat == n) & (curve.arm == a)].test_fscore.mean() for n in SIZES for a in ARMS}
gap = lambda n, a: 100.0 * (mean_cd[(n, a)] - mean_cd[(n, "A_geo")]) / mean_cd[(n, "A_geo")]

n150 = curve[curve.n_per_cat == 150]
seed_gaps = []  # per-seed C-vs-A gap at the top rung
for s in sorted(n150.seed.unique()):
    a = n150[(n150.arm == "A_geo") & (n150.seed == s)].test_cd_l1.iloc[0]
    c = n150[(n150.arm == "C_colin") & (n150.seed == s)].test_cd_l1.iloc[0]
    seed_gaps.append(100.0 * (c - a) / a)

cmse = {n: curve[(curve.n_per_cat == n) & (curve.arm == "B_joint")].test_color_mse.mean() for n in SIZES}
base = {k: curve[f"base_{k}"].iloc[0] for k in ["nn", "mean", "median"]}
oracle = curve.test_color_oracle.dropna().mean()
epochs_trained = {r: int(m.epoch.max()) + 1 for r, m in metrics.items()}

# ---------------- numbers.tex ----------------
f1 = lambda x: f"{x:.1f}"
f2 = lambda x: f"{x:.2f}"
f3 = lambda x: f"{x:.3f}"
WORD = {20: "twenty", 60: "sixty", 150: "onefifty"}
L = ["% AUTO-GENERATED by make_figures.py from runs/curve.csv + runs/*/metrics.csv on HF.",
     "% Every number quoted in the report's prose lives here. Do not edit by hand."]
for n in SIZES:
    for a, short in [("A_geo", "A"), ("B_joint", "B"), ("C_colin", "C")]:
        L.append(f"\\newcommand*\\cd{short}{WORD[n]}{{{f2(mean_cd[(n, a)])}}}")
    L.append(f"\\newcommand*\\gapC{WORD[n]}{{{f1(gap(n, 'C_colin'))}}}")
    L.append(f"\\newcommand*\\gapB{WORD[n]}{{{f1(gap(n, 'B_joint'))}}}")
    L.append(f"\\newcommand*\\cmseB{WORD[n]}{{{f3(cmse[n])}}}")
for name, g in zip(["gapCseedOne", "gapCseedTwo", "gapCseedThree"], sorted(seed_gaps)):
    L.append(f"\\newcommand*\\{name}{{{f1(g)}}}")
L += [f"\\newcommand*\\fsAonefifty{{{f2(mean_fs[(150, 'A_geo')])}}}",
      f"\\newcommand*\\fsConefifty{{{f2(mean_fs[(150, 'C_colin')])}}}",
      f"\\newcommand*\\fsBonefifty{{{f2(mean_fs[(150, 'B_joint')])}}}",
      f"\\newcommand*\\cdAonefiftyLo{{{f2(n150[n150.arm == 'A_geo'].test_cd_l1.min())}}}",
      f"\\newcommand*\\cdAonefiftyHi{{{f2(n150[n150.arm == 'A_geo'].test_cd_l1.max())}}}",
      f"\\newcommand*\\cmseNN{{{f3(base['nn'])}}}",
      f"\\newcommand*\\cmseMean{{{f3(base['mean'])}}}",
      f"\\newcommand*\\cmseMedian{{{f3(base['median'])}}}",
      f"\\newcommand*\\cmseOracle{{{f3(oracle)}}}",
      f"\\newcommand*\\nBundles{{{n_bundles}}}",
      f"\\newcommand*\\nRuns{{{len(curve)}}}",
      f"\\newcommand*\\nTrainLow{{{int(curve[curve.n_per_cat == 20].n_train_models.iloc[0])}}}",
      f"\\newcommand*\\nTrainMid{{{int(curve[curve.n_per_cat == 60].n_train_models.iloc[0])}}}",
      f"\\newcommand*\\nTrainTop{{{int(curve[curve.n_per_cat == 150].n_train_models.iloc[0])}}}",
      f"\\newcommand*\\totalEpochs{{{sum(epochs_trained.values())}}}",
      f"\\newcommand*\\epochsMin{{{min(epochs_trained.values())}}}",
      f"\\newcommand*\\epochsMax{{{max(epochs_trained.values())}}}",
      f"\\newcommand*\\datasetRev{{{dataset_sha[:10]}}}"]
with open(os.path.join(GEN, "numbers.tex"), "w") as fh:
    fh.write("\n".join(L) + "\n")

# sanity: an independently recomputed headline gap must match the emitted macro
assert f1(100 * (25.250112016995747 - 23.678491295625765) / 23.678491295625765) == f1(gap(20, "C_colin"))

# ---------------- runs_table.tex ----------------
rows = ["% AUTO-GENERATED by make_figures.py — the 15 runs, verbatim from runs/curve.csv.",
        "\\begin{tabular}{llrrrrrrrr}", "\\toprule",
        "run & arm & $N$/cat & seed & CD-L1 & CD-L2 & F@1\\% & color MSE & best ep & ep trained \\\\",
        "\\midrule"]
for n in SIZES:
    for a in ARMS:
        for _, r in curve[(curve.n_per_cat == n) & (curve.arm == a)].sort_values("seed").iterrows():
            cm = f3(r.test_color_mse) if pd.notna(r.test_color_mse) else "--"
            rows.append(f"\\runname{{{r.run.replace('_', '\\_')}}} & \\arm{{{a.replace('_', '\\_')}}} & {n} & "
                        f"{int(r.seed)} & {f2(r.test_cd_l1)} & {f3(r.test_cd_l2)} & {f3(r.test_fscore)} & "
                        f"{cm} & {int(r.best_epoch)} & {epochs_trained[r.run]} \\\\")
    if n != SIZES[-1]:
        rows.append("\\midrule")
rows += ["\\bottomrule", "\\end{tabular}"]
with open(os.path.join(GEN, "runs_table.tex"), "w") as fh:
    fh.write("\n".join(rows) + "\n")

# ---------------- fig_curve ----------------
plt.rcParams.update({"font.size": 9, "axes.spines.top": False, "axes.spines.right": False})
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(9.0, 3.3))
for a in ARMS:
    col, mk, lab = ARM_STYLE[a]
    ax1.plot(SIZES, [mean_cd[(n, a)] for n in SIZES], marker=mk, ms=5, color=col, label=lab, lw=1.6)
    sub = n150[n150.arm == a]
    ax1.scatter([150] * len(sub), sub.test_cd_l1, s=14, color=col, alpha=0.45, zorder=3)
logx(ax1)
ax1.set_xticks(SIZES, [str(n) for n in SIZES])
ax1.set_xlabel("training models per category $N$")
ax1.set_ylabel("test CD-L1 ($\\times 10^3$, lower is better)")
ax1.set_title("Completion quality vs. data scale", fontsize=9.5)
ax1.legend(frameon=False, fontsize=8)
for a in ["C_colin", "B_joint"]:
    col, mk, lab = ARM_STYLE[a]
    ax2.plot(SIZES, [gap(n, a) for n in SIZES], marker=mk, ms=5, color=col, lw=1.6,
             label=lab.split(" ")[0] + " vs. A_geo")
ax2.scatter([150] * len(seed_gaps), seed_gaps, s=14, color=ARM_STYLE["C_colin"][0], alpha=0.45, zorder=3)
ax2.axhline(0, color="0.55", lw=0.9, ls="--")
ax2.annotate("no harm", (SIZES[0], 0), textcoords="offset points", xytext=(2, 3), fontsize=7.5, color="0.4")
logx(ax2)
ax2.set_xticks(SIZES, [str(n) for n in SIZES])
ax2.set_xlabel("training models per category $N$")
ax2.set_ylabel("CD-L1 gap vs. A_geo (%, $>0$ = worse)")
ax2.set_title("The color-input harm shrinks, but does not flip", fontsize=9.5)
ax2.set_ylim(-1, 8)
ax2.legend(frameon=False, fontsize=8)
fig.tight_layout()
fig.savefig(os.path.join(FIG, "fig_curve.pdf"))
plt.close(fig)

# ---------------- fig_color ----------------
fig, ax = plt.subplots(figsize=(4.6, 3.1))
ax.plot(SIZES, [cmse[n] for n in SIZES], marker="^", color=ARM_STYLE["B_joint"][0], lw=1.6,
        label="learned color head (B_joint)")
for k, ls, dy, lab in [("nn", ":", 5, "NN-copy"), ("median", "-.", -11, "median-copy"), ("mean", "--", -11, "mean-copy")]:
    ax.axhline(base[k], color="0.35", ls=ls, lw=1.0)
    ax.annotate(lab, (SIZES[-1], base[k]), textcoords="offset points", xytext=(4, dy), fontsize=7.5, color="0.35")
ax.axhline(oracle, color="#8B0000", ls="-", lw=1.0, alpha=0.6)
ax.annotate("oracle floor", (SIZES[-1], oracle), textcoords="offset points", xytext=(4, 2), fontsize=7.5,
            color="#8B0000")
logx(ax)
ax.set_xticks(SIZES, [str(n) for n in SIZES])
ax.set_xlim(17, 320)
ax.set_xlabel("training models per category $N$")
ax.set_ylabel("test color MSE (lower is better)")
ax.set_title("Learned color vs. training-free copy baselines", fontsize=9.5)
ax.legend(frameon=False, fontsize=8, loc="center left")
fig.tight_layout()
fig.savefig(os.path.join(FIG, "fig_color.pdf"))
plt.close(fig)

# ---------------- fig_training (appendix small-multiples) ----------------
order = [f"n{n:03d}_{a}_s{s}" for n, seeds in [(20, [1234]), (60, [1234]), (150, [1234, 2, 3])]
         for s in seeds for a in ARMS]
fig, axes = plt.subplots(5, 3, figsize=(9.0, 10.5), sharex=False)
for ax, r in zip(axes.flat, order):
    m = metrics[r]
    ax.plot(m.epoch, m.cd_fine_l1, color="0.75", lw=0.9, label="train")
    v = m.dropna(subset=["val_cd_l1"])
    ax.plot(v.epoch, v.val_cd_l1, color="#1F3A5F", lw=1.3, marker=".", ms=3, label="val")
    be = int(curve[curve.run == r].best_epoch.iloc[0])
    ax.axvline(be, color="#C05621", lw=0.9, ls="--")
    ax.set_title(r, fontsize=7.5)
    ax.tick_params(labelsize=7)
axes[0, 0].legend(frameon=False, fontsize=7)
for ax in axes[-1]:
    ax.set_xlabel("epoch", fontsize=8)
for row in axes:
    row[0].set_ylabel("CD-L1 $\\times 10^3$", fontsize=8)
fig.suptitle("All 15 runs: train/val CD-L1 per epoch (dashed line = best epoch kept by early stopping)",
             fontsize=10)
fig.tight_layout(rect=(0, 0, 1, 0.98))
fig.savefig(os.path.join(FIG, "fig_training.pdf"))
plt.close(fig)

# ---------------- fig_panels (qualitative composite from the run's own renders) ----------------
# Each source panel PNG is [partial | coarse | fine | GT] in 4 equal columns for one test
# shape; panels with the same index share the shape across arms. Recompose (no re-rendering):
# columns partial + GT from the A panel, plus each arm's fine output. The run rendered
# views 00-02 of the FIRST held-out test shape (same GT across rows).
def col(img, i, y0=100):
    w = img.width // 4
    return img.crop((i * w, y0, (i + 1) * w, img.height))

views = ["00", "01", "02"]
cols_titles = ["input partial", "ground truth", "A_geo output", "C_colin output", "B_joint output\n(predicted color)"]
fig, axes = plt.subplots(len(views), 5, figsize=(10.0, 2.15 * len(views)))
for row, sh in enumerate(views):
    imgs = {a: Image.open(dl(f"runs/panel_{a}_{sh}.png")) for a in ARMS}
    cells = [col(imgs["A_geo"], 0), col(imgs["A_geo"], 3), col(imgs["A_geo"], 2),
             col(imgs["C_colin"], 2), col(imgs["B_joint"], 2)]
    for c, (ax, im) in enumerate(zip(axes[row], cells)):
        ax.imshow(im)
        ax.axis("off")
        if row == 0:
            ax.set_title(cols_titles[c], fontsize=8)
    axes[row][0].text(-0.06, 0.5, f"input view {sh}", transform=axes[row][0].transAxes,
                      rotation=90, va="center", ha="center", fontsize=8)
fig.suptitle("One held-out test shape at the top rung ($N{=}150$): three input views, all three arms", fontsize=10)
fig.tight_layout(rect=(0, 0, 1, 0.97))
fig.savefig(os.path.join(FIG, "fig_panels.png"), dpi=220)
plt.close(fig)

print("wrote:", sorted(os.listdir(FIG)), "+", sorted(os.listdir(GEN)))
print(f"dataset revision {dataset_sha[:10]} | {n_bundles} bundles | {len(curve)} runs | "
      f"total epochs {sum(epochs_trained.values())}")
