#!/usr/bin/env python3
"""Build every figure and every quoted number of the 2026-08-19 weekly report (s7 RePaint
color inpainting) from the run artifacts on HF (`efeyenice/pc-completion-data`, public).

Prose numbers are emitted as LaTeX macros (generated/numbers.tex) so the report text cannot
drift from the data. Aggregation reuses the tested helpers in tools/pc_repaint.py
(`read_rows`, `summarize_rows`) rather than re-deriving it here.
"""
import os
import sys

import numpy as np
import pandas as pd

os.environ.setdefault("SOURCE_DATE_EPOCH", "1786752000")  # deterministic PDF metadata
import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.patches import Patch
from PIL import Image
from huggingface_hub import HfApi, hf_hub_download

HERE = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
# flat import: PoinTr ships a regular `tools` package that would shadow ours (PR #20)
sys.path.insert(0, os.path.join(REPO_ROOT, "tools"))
from pc_repaint import read_rows, summarize_rows  # noqa: E402

REPO = "efeyenice/pc-completion-data"
FIG = os.path.join(HERE, "figures")
GEN = os.path.join(HERE, "generated")
os.makedirs(FIG, exist_ok=True)
os.makedirs(GEN, exist_ok=True)

# ---------------------------------------------------------------- config
STAGES = {"S": "auto", "R": "labeled_s3"}           # macro prefix -> CSV stage
STAGE_LABEL = {"S": "synthetic palette", "R": "real texture"}
PANEL = {"S": "runs/repaint/panel_auto_bdfbf1c555.png",
         "R": "runs/repaint/panel_labeled_s3_bdeb0a21cf.png"}

VAR = {"NN": "NN-copy", "PM": "part-mean", "RV": "RePaint-vanilla",
       "RP": "RePaint-part", "RO": "RePaint-part (oracle seg)", "OC": "oracle ceiling"}
CROP = {"Lo": 0.25, "Mid": 0.50, "Hi": 0.75}
CROPS = [0.25, 0.50, 0.75]
BASELINES = ["NN-copy", "part-mean"]
DIFFUSION = ["RePaint-vanilla", "RePaint-part", "RePaint-part (oracle seg)"]

NAVY, ACCENT, ORANGE, GREEN, DARKRED = "#1F3A5F", "#2B6CB0", "#C05621", "#2E7D32", "#8B0000"
STYLE = {  # color, marker, linestyle
    "NN-copy": ("#8A8A8A", "o", "-"),
    "part-mean": ("#4F4F4F", "s", "-"),
    "oracle ceiling": (DARKRED, "", "--"),
    "RePaint-part": (NAVY, "D", "-"),
    "RePaint-vanilla": (ORANGE, "^", "-"),
    "RePaint-part (oracle seg)": (ACCENT, "v", ":"),
}

# Figures are sized close to the report's text width (~6.4in) so LaTeX barely downscales
# them and the labels stay legible on the page.
plt.rcParams.update({"font.size": 9.5, "axes.spines.top": False, "axes.spines.right": False})


def dl(path):
    return hf_hub_download(REPO, path, repo_type="dataset")


# ---------------------------------------------------------------- data
SUM, RAW = {}, {}
for st, stage in STAGES.items():
    path = dl(f"runs/repaint/eval_rows_{stage}.csv")
    SUM[st] = summarize_rows(read_rows(path))
    RAW[st] = pd.read_csv(path)

api = HfApi()
dataset_sha = api.dataset_info(REPO).sha
n_labeled = sum(1 for f in api.list_repo_files(REPO, repo_type="dataset")
                if f.startswith("data_labeled/02691156/") and f.endswith(".npz"))


def s(st, table, crop, variant, field="mean"):
    return SUM[st][(table, crop, variant)][field]


def has(st, table, crop, variant):
    return (table, crop, variant) in SUM[st]


def n_models(st, table="E1", crop=0.50):
    return SUM[st][(table, crop, "RePaint-part")]["n_models"]


def best_baseline(st, table="E1", crop=0.50):
    """The stronger of the two trivial rules at this cell (lower ΔE = better)."""
    return min(BASELINES, key=lambda v: s(st, table, crop, v))


def per_model(st, table="E1", crop=0.50):
    """(model x variant) table of mean-over-seeds ΔE."""
    d = RAW[st]
    d = d[(d.table == table) & (np.isclose(d.crop, crop))]
    return d.groupby(["model_id", "variant"]).value.mean().unstack()


def wins(st, table="E1", crop=0.50):
    """(n_wins, n_models) for RePaint-part vs the better trivial baseline, per model."""
    pm = per_model(st, table, crop)
    return int((pm["RePaint-part"] < pm[BASELINES].min(axis=1)).sum()), int(len(pm))


headroom = {st: s(st, "E1", 0.50, best_baseline(st)) - s(st, "E1", 0.50, "oracle ceiling")
            for st in STAGES}

# ---------------------------------------------------------------- numbers.tex
f1 = lambda x: f"{x:.1f}"
f2 = lambda x: f"{x:.2f}"

L = ["% AUTO-GENERATED by make_figures.py from runs/repaint/eval_rows_{auto,labeled_s3}.csv on HF.",
     "% Every number quoted in the report's prose lives here. Do not edit by hand.",
     "%",
     "% Naming: \\dE<Stage><Variant><Crop>  mean-of-seeds Delta-E",
     "%         \\bok<Stage><Variant><Crop>  best-of-k (min over seeds)",
     "%         \\dv<Stage><Variant><Crop>   sample diversity (mean pairwise Delta-E)",
     "%         \\eII<Stage><Variant>        E2 (one part fully occluded), 50% crop",
     "%   Stage    : S = synthetic palette, R = real texture",
     "%   Variant  : NN, PM (part-mean), RV (vanilla), RP (part), RO (part, oracle seg), OC (ceiling)",
     "%   Crop     : Lo = 25%, Mid = 50%, Hi = 75%",
     ""]

for st in STAGES:
    for vk, vname in VAR.items():
        for ck, crop in CROP.items():
            if has(st, "E1", crop, vname):
                L.append(f"\\newcommand*\\dE{st}{vk}{ck}{{{f1(s(st, 'E1', crop, vname))}}}")
                L.append(f"\\newcommand*\\bok{st}{vk}{ck}{{{f1(s(st, 'E1', crop, vname, 'best_mean'))}}}")
            if has(st, "DIV", crop, vname):
                L.append(f"\\newcommand*\\dv{st}{vk}{ck}{{{f1(s(st, 'DIV', crop, vname))}}}")
        if has(st, "E2", 0.50, vname):
            L.append(f"\\newcommand*\\eII{st}{vk}{{{f1(s(st, 'E2', 0.50, vname))}}}")

for st in STAGES:
    w, n = wins(st)
    w2, n2 = wins(st, "E2", 0.50)
    L += [f"\\newcommand*\\win{st}{{{w}}}",
          f"\\newcommand*\\winN{st}{{{n}}}",
          f"\\newcommand*\\winE{st}{{{w2}}}",
          f"\\newcommand*\\winEN{st}{{{n2}}}",
          f"\\newcommand*\\hdrm{st}{{{f1(headroom[st])}}}",
          f"\\newcommand*\\nrows{st}{{{len(RAW[st]):,}}}".replace(",", "{,}"),
          f"\\newcommand*\\nmod{st}{{{n_models(st)}}}",
          f"\\newcommand*\\bestbase{st}{{{best_baseline(st)}}}"]

# ratio of the method to the better trivial baseline — the through-line quantity
for st in STAGES:
    L.append(f"\\newcommand*\\ratio{st}{{{f2(s(st, 'E1', 0.50, 'RePaint-part') / s(st, 'E1', 0.50, best_baseline(st)))}}}")

L += [f"\\newcommand*\\nLabeled{{{n_labeled}}}",
      f"\\newcommand*\\datasetRev{{{dataset_sha[:10]}}}",
      f"\\newcommand*\\hdrmRatio{{{f1(headroom['S'] / headroom['R'])}}}",
      f"\\newcommand*\\dvRatio{{{f1(s('R', 'DIV', 0.50, 'RePaint-part') / s('S', 'DIV', 0.50, 'RePaint-part'))}}}"]

# s6 regression anchor (previous report's artifacts, same HF repo) — for the through-line
# table. s5 predates the HF-native pipeline and its magnitude is superseded (ADR-0007
# Outcome), so it is quoted qualitatively only, never as a numeral.
curve = pd.read_csv(dl("runs/curve.csv"))
six_learned = curve[(curve.n_per_cat == 150) & (curve.arm == "B_joint")].test_color_mse.mean()
six_mean = float(curve["base_mean"].iloc[0])
# 4 d.p. so that the quoted ratio is verifiable from the two numbers printed beside it
L += [f"\\newcommand*\\sixLearned{{{six_learned:.4f}}}",
      f"\\newcommand*\\sixMean{{{six_mean:.4f}}}",
      f"\\newcommand*\\sixRatio{{{six_learned / six_mean:.3f}}}"]

with open(os.path.join(GEN, "numbers.tex"), "w") as fh:
    fh.write("\n".join(L) + "\n")

# sanity: an independently recomputed headline must match the emitted macro
_chk = RAW["R"]
_chk = _chk[(_chk.table == "E1") & (np.isclose(_chk.crop, 0.5)) & (_chk.variant == "RePaint-part")]
assert f1(_chk.groupby("model_id").value.mean().mean()) == f1(s("R", "E1", 0.50, "RePaint-part"))
assert wins("R")[0] == 0, "real-texture win count changed"

# ---------------------------------------------------------------- sweep_table.tex
rows = ["% AUTO-GENERATED by make_figures.py — the full E1/E2 sweep, both stages.",
        "\\begin{tabular}{llrrrrrr}", "\\toprule",
        "& & \\multicolumn{3}{c}{synthetic palette} & \\multicolumn{3}{c}{real texture} \\\\",
        "\\cmidrule(lr){3-5}\\cmidrule(lr){6-8}",
        "table & variant & 25\\% & 50\\% & 75\\% & 25\\% & 50\\% & 75\\% \\\\", "\\midrule"]
for tbl in ["E1", "E2"]:
    for vname in ["NN-copy", "part-mean", "oracle ceiling", "RePaint-vanilla",
                  "RePaint-part", "RePaint-part (oracle seg)"]:
        cells = []
        for st in ["S", "R"]:
            for crop in CROPS:
                cells.append(f1(s(st, tbl, crop, vname)) if has(st, tbl, crop, vname) else "--")
        if set(cells) == {"--"}:
            continue
        rows.append(f"{tbl} & {vname.replace('%', '\\%')} & " + " & ".join(cells) + " \\\\")
    rows.append("\\midrule")
for vname in DIFFUSION:
    cells = [f1(s(st, "DIV", crop, vname)) if has(st, "DIV", crop, vname) else "--"
             for st in ["S", "R"] for crop in CROPS]
    rows.append(f"DIV & {vname} & " + " & ".join(cells) + " \\\\")
rows += ["\\bottomrule", "\\end{tabular}"]
with open(os.path.join(GEN, "sweep_table.tex"), "w") as fh:
    fh.write("\n".join(rows) + "\n")

# ---------------------------------------------------------------- F1 · headroom collapse
fig, ax = plt.subplots(figsize=(7.4, 2.7))
YPOS = {"S": 1.0, "R": 0.0}
for st, y in YPOS.items():
    ceil = s(st, "E1", 0.50, "oracle ceiling")
    base = s(st, "E1", 0.50, best_baseline(st))
    meth = s(st, "E1", 0.50, "RePaint-part")
    ax.barh(y, base - ceil, left=ceil, height=0.34, color=GREEN, alpha=0.20,
            edgecolor=GREEN, linewidth=1.0, zorder=2)
    ax.plot([ceil], [y], marker="|", ms=17, mew=2.4, color=DARKRED, zorder=4)
    ax.plot([base], [y], marker="|", ms=17, mew=2.4, color="#4F4F4F", zorder=4)
    ax.plot([meth], [y], marker="D", ms=8, color=NAVY, zorder=5)
    # two annotation levels above the bar (prize, then method) and one below (band ends),
    # so nothing collides even when the band is only a few Delta-E wide
    ax.annotate(f"prize = {headroom[st]:.1f} $\\Delta$E", ((ceil + base) / 2, y + 0.42),
                ha="center", fontsize=8.5, color=GREEN, fontweight="bold")
    ax.annotate(f"RePaint-part {meth:.1f}", (meth, y + 0.17), ha="center",
                fontsize=8.2, color=NAVY, fontweight="bold")
    # narrow band (real texture): push the two end-labels apart with opposite alignment
    tight = (base - ceil) < 10
    ax.annotate(f"ceiling {ceil:.1f}", (ceil - 1.0 if tight else ceil, y - 0.30),
                ha="right" if tight else "center", fontsize=7.6, color=DARKRED)
    ax.annotate(f"best rule {base:.1f}", (base + 1.0 if tight else base, y - 0.30),
                ha="left" if tight else "center", fontsize=7.6, color="#4F4F4F")
    if meth > base:  # method sits outside the band — draw the miss
        ax.annotate("", xy=(meth - 1.2, y), xytext=(base + 1.2, y),
                    arrowprops=dict(arrowstyle="->", color=NAVY, lw=1.3, ls=":"))
ax.set_yticks([0, 1], [f"real texture\n({n_models('R')} models)",
                       f"synthetic palette\n({n_models('S')} models)"], fontsize=8.5)
ax.set_ylim(-0.62, 1.82)
ax.set_xlim(0, 88)
ax.set_xlabel("mean $\\Delta$E(Lab) on the missing region at 50% occlusion "
              "(lower is better; ~2 = just noticeable)")
ax.set_title("The prize collapses on real texture: the whole part-colour model class has "
             f"{headroom['S'] / headroom['R']:.0f}$\\times$ less to win", fontsize=10, color=NAVY)
ax.legend(handles=[Patch(facecolor=GREEN, alpha=0.25, edgecolor=GREEN,
                         label="everything a part-colour method could possibly gain")],
          frameon=False, fontsize=8, loc="lower right")
ax.spines["left"].set_visible(False)
ax.tick_params(axis="y", length=0)
fig.tight_layout()
fig.savefig(os.path.join(FIG, "fig_headroom.pdf"))
plt.close(fig)

# ---------------------------------------------------------------- F2 · the scissors
fig, axes = plt.subplots(1, 2, figsize=(7.4, 3.1), sharey=True)
x = [25, 50, 75]
for ax, st in zip(axes, ["S", "R"]):
    for vname in ["NN-copy", "part-mean", "oracle ceiling", "RePaint-vanilla", "RePaint-part"]:
        col, mk, ls = STYLE[vname]
        ax.plot(x, [s(st, "E1", c, vname) for c in CROPS], marker=mk or None, ms=5,
                color=col, ls=ls, lw=1.9 if vname == "RePaint-part" else 1.3,
                label=vname, zorder=4 if vname == "RePaint-part" else 3)
    ax.set_xticks(x, [f"{v}%" for v in x])
    ax.set_xlabel("occlusion (% of points missing)")
    ax.set_title(STAGE_LABEL[st], fontsize=9.5,
                 color=GREEN if st == "S" else DARKRED)
axes[0].set_ylabel("mean $\\Delta$E(Lab), missing region")
axes[0].legend(frameon=False, fontsize=7.6, loc="upper left")
axes[0].annotate("prior holds; rules decay", (50, 30), fontsize=8, color=GREEN, ha="center")
axes[1].annotate("rules hold; prior decays", (50, 45), fontsize=8, color=DARKRED, ha="center")
fig.suptitle("Same code, opposite behaviour: what happens as more colour is hidden",
             fontsize=10.5, color=NAVY)
fig.tight_layout(rect=(0, 0, 1, 0.94))
fig.savefig(os.path.join(FIG, "fig_scissors.pdf"))
plt.close(fig)

# ---------------------------------------------------------------- F3 · qualitative panels
TITLES = ["occluded input", "NN-copy", "part-mean", "RePaint-vanilla", "RePaint-part", "ground truth"]
Y0 = 42  # crop the renderer's own baked-in titles (measured: text occupies rows 10-39)
fig, axes = plt.subplots(2, 6, figsize=(7.8, 3.0))
for r, st in enumerate(["S", "R"]):
    im = Image.open(dl(PANEL[st]))
    w = im.width // 6
    for c in range(6):
        ax = axes[r][c]
        ax.imshow(im.crop((c * w, Y0, (c + 1) * w, im.height)))
        ax.axis("off")
        if r == 0:
            ax.set_title(TITLES[c], fontsize=8.5)
    axes[r][0].text(-0.08, 0.5, STAGE_LABEL[st], transform=axes[r][0].transAxes,
                    rotation=90, va="center", ha="center", fontsize=8.5,
                    color=GREEN if st == "S" else DARKRED, fontweight="bold")
fig.suptitle("One held-out test aeroplane per stage, 50% occluded "
             "(the two centre-right columns are the diffusion prior's answer)", fontsize=9.5)
fig.tight_layout(rect=(0, 0, 1, 0.95))
fig.savefig(os.path.join(FIG, "fig_panels.png"), dpi=220)
plt.close(fig)

# ---------------------------------------------------------------- F4 · per-model win/loss
fig, ax = plt.subplots(figsize=(4.5, 4.0))
for st, col, lab in [("S", GREEN, STAGE_LABEL["S"]), ("R", DARKRED, STAGE_LABEL["R"])]:
    pm = per_model(st)
    xb, ym = pm[BASELINES].min(axis=1), pm["RePaint-part"]
    w, n = wins(st)
    ax.scatter(xb, ym, s=15, color=col, alpha=0.55, edgecolor="none",
               label=f"{lab} — wins {w}/{n}")
lims = [0, 105]
ax.plot(lims, lims, color="0.45", lw=1.0, ls="--")
ax.annotate("ties", (95, 97), fontsize=7.5, color="0.45", rotation=45, ha="center")
ax.annotate("RePaint-part wins\n(below the line)", (72, 22), fontsize=8, color=GREEN, ha="center")
ax.annotate("baseline wins\n(above the line)", (30, 88), fontsize=8, color=DARKRED, ha="center")
ax.set_xlim(lims)
ax.set_ylim(lims)
ax.set_aspect("equal")
ax.set_xlabel("better trivial baseline, $\\Delta$E")
ax.set_ylabel("RePaint-part, $\\Delta$E")
ax.set_title("Every test model, 50% occlusion", fontsize=9.5)
ax.legend(frameon=False, fontsize=7.8, loc="lower right")
fig.tight_layout()
fig.savefig(os.path.join(FIG, "fig_winloss.pdf"))
plt.close(fig)

# ---------------------------------------------------------------- F5 · part-conditioning sign flip
fig, ax = plt.subplots(figsize=(4.5, 2.9))
cats = ["25%", "50%", "75%", "E2\n(part gone)"]
xs = np.arange(len(cats))
for st, col, lab in [("S", GREEN, STAGE_LABEL["S"]), ("R", DARKRED, STAGE_LABEL["R"])]:
    adv = [s(st, "E1", c, "RePaint-vanilla") - s(st, "E1", c, "RePaint-part") for c in CROPS]
    adv.append(s(st, "E2", 0.50, "RePaint-vanilla") - s(st, "E2", 0.50, "RePaint-part"))
    ax.plot(xs, adv, marker="o", ms=6, color=col, lw=1.8, label=lab)
ax.axhline(0, color="0.45", lw=1.0, ls="--")
ax.annotate("part-conditioning HELPS", (0.04, 0.90), xycoords="axes fraction",
            fontsize=8, color=GREEN, fontweight="bold")
ax.annotate("part-conditioning HURTS", (0.04, 0.06), xycoords="axes fraction",
            fontsize=8, color=DARKRED, fontweight="bold")
ax.set_xticks(xs, cats)
ax.set_ylabel("$\\Delta$E gained by part-conditioning\n(vanilla $-$ part)")
ax.set_title("The same design choice flips sign with the data", fontsize=9.5)
ax.legend(frameon=False, fontsize=8, loc="lower left")
fig.tight_layout()
fig.savefig(os.path.join(FIG, "fig_signflip.pdf"))
plt.close(fig)

# ---------------------------------------------------------------- F6 · the four controls
fig, axes2d = plt.subplots(2, 2, figsize=(6.6, 4.3))
axes = axes2d.ravel()
bar_kw = dict(width=0.62, zorder=3)

ax = axes[0]  # (1) not the segmenter
v = [s("R", "E1", 0.50, "RePaint-part"), s("R", "E1", 0.50, "RePaint-part (oracle seg)")]
ax.bar([0, 1], v, color=[NAVY, ACCENT], **bar_kw)
ax.axhline(s("R", "E1", 0.50, best_baseline("R")), color=DARKRED, lw=1.2, ls="--")
ax.set_xticks([0, 1], ["predicted\nlabels", "perfect\nlabels"], fontsize=8)
ax.set_title("1 · not the segmenter", fontsize=9, color=NAVY)
ax.annotate("best trivial rule", (0.5, s("R", "E1", 0.50, best_baseline("R")) + 6.0),
            fontsize=7.5, color=DARKRED, ha="center")

ax = axes[1]  # (2) not sampling luck
v = [s("R", "E1", 0.50, "RePaint-part"), s("R", "E1", 0.50, "RePaint-part", "best_mean")]
ax.bar([0, 1], v, color=[NAVY, ACCENT], **bar_kw)
ax.axhline(s("R", "E1", 0.50, best_baseline("R")), color=DARKRED, lw=1.2, ls="--")
ax.set_xticks([0, 1], ["mean of\n5 seeds", "best of\n5 seeds"], fontsize=8)
ax.set_title("2 · not sampling luck", fontsize=9, color=NAVY)

ax = axes[2]  # (3) the prior is uncommitted
v = [s("S", "DIV", 0.50, "RePaint-part"), s("R", "DIV", 0.50, "RePaint-part")]
ax.bar([0, 1], v, color=[GREEN, DARKRED], **bar_kw)
ax.set_xticks([0, 1], ["synthetic", "real"], fontsize=8)
ax.set_title("3 · scattered samples", fontsize=9, color=NAVY)
ax.set_ylabel("pairwise $\\Delta$E", fontsize=8)

ax = axes[3]  # (4) the code is fine
v = [s("S", "E1", 0.50, "RePaint-part"), s("S", "E1", 0.50, best_baseline("S"))]
ax.bar([0, 1], v, color=[NAVY, "#4F4F4F"], **bar_kw)
ax.set_xticks([0, 1], ["RePaint\npart", "best\nrule"], fontsize=8)
ax.set_title("4 · same code wins\non synthetic", fontsize=9, color=NAVY)

for a in axes2d.flat:
    a.tick_params(axis="y", labelsize=8)
axes2d[0][0].set_ylabel("mean $\\Delta$E", fontsize=8.5)
axes2d[1][1].set_ylabel("mean $\\Delta$E", fontsize=8.5)
fig.suptitle("Four controls, four mundane explanations ruled out", fontsize=11, color=NAVY)
fig.tight_layout(rect=(0, 0, 1, 0.93))
fig.savefig(os.path.join(FIG, "fig_controls.pdf"))
plt.close(fig)

# ---------------------------------------------------------------- report
print("wrote:", sorted(os.listdir(FIG)), "+", sorted(os.listdir(GEN)))
for st in STAGES:
    w, n = wins(st)
    print(f"  {STAGE_LABEL[st]:18s} RePaint-part {s(st, 'E1', 0.50, 'RePaint-part'):5.1f} | "
          f"best rule {s(st, 'E1', 0.50, best_baseline(st)):5.1f} ({best_baseline(st)}) | "
          f"ceiling {s(st, 'E1', 0.50, 'oracle ceiling'):5.1f} | "
          f"prize {headroom[st]:5.1f} | wins {w}/{n}")
print(f"  dataset revision {dataset_sha[:10]} | {n_labeled} fused labeled models")
